### ISSUE TITLE
Set query parameter value as array

### ISSUE THREAD

**Issue by jpbarbosa** [adam-cowley/neo4j-vscode#2]
How may I set a query parameter value as an array?

<table>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/2099381/218175067-815fb265-3c46-4aa1-8ace-4a126de03796.png"></td>
    <td><img src="https://user-images.githubusercontent.com/2099381/218175092-86a8535d-b104-4208-bc79-afbc52cf4fd3.png"></td>
  </tr>
</table>

**Comment by adam-cowley** [comment]
When you use `JSON or OBJECT` the value is parsed with `JSON.parse` so that should also work for arrays.  I will update the description.

**Comment by jpbarbosa** [comment]
Yeah, it worked. Thank you.
