### ISSUE TITLE
Please consider publishing to the Open VSX Registry

### ISSUE THREAD

**Issue by JDDurrant** [adam-cowley/neo4j-vscode#3]
Please consider publishing to the [Open VSX Registry](https://open-vsx.org/).

I use [VSCodium](https://vscodium.com/) because I want to use a _truly_ open source code editor. The official VS Code binaries are proprietary, and they contain analytics code, which invades user privacy and slows the program down.

Unfortunately, due to licensing, only the official VS Code binaries are allowed to download extensions from the Visual Studio Marketplace. Because of this, as a VSCodium user, I depend on the Open VSX Registry for my extensions.

I hope you'll consider publishing your extension there.

**Comment by adam-cowley** [comment]
Great idea.  [Here you go!](https://open-vsx.org/extension/adamcowley/neo4j-vscode)

**Comment by JDDurrant** [comment]
Cheers, much appreciated 👊

Closing.
